# core module, mustn't remove
- name: highlight.js
  style-url:
      - 'https://cdn.jsdelivr.net/npm/highlight.js@10/styles/default.min.css'

# core module, mustn't remove
- name: slide
  module: './markdown-it-plugin/markdown-it-slide'

# core module, mustn't remove
- name: webslides
  static:
      - 'webslides'
  style-url:
      - '/webslides/css/webslides.css'
  script-url:
      - '/webslides/js/webslides.js'

# core module, mustn't remove
- name: slide-meta
  module: './markdown-it-plugin/markdown-it-slide-meta'

# basic module, not recommend remove
- name: slide-container
  module: './markdown-it-plugin/markdown-it-slide-container'

# basic module, not recommend remove
- name: attrs
  module: 'markdown-it-attrs'

# basic module, not recommend remove
- name: span
  module: 'markdown-it-bracketed-spans'

# optional
- name: colors.css
  style-url:
      - 'https://cdn.jsdelivr.net/npm/colors.css@3/css/colors.min.css'

# optional
- name: easy-font
  module: './markdown-it-plugin/easy-font'
- name: easy-font-render
  type: render
  module: './markdown-it-plugin/easy-font-render'

# optional
- name: font-awesome
  module: 'markdown-it-fontawesome'
  style-url:
      - 'https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5/css/all.min.css'

# optional
- name: animate.css
  style-url:
      - 'https://cdn.jsdelivr.net/npm/animate.css@4/animate.compat.css'

# optional
- name: webslides-animation
  static:
      - 'webslides-animation'
  script-url:
      - '/webslides-animation/webslides-animation.js'
      - '/webslides-animation/index.js'

# optional
- name: ruby
  module: 'markdown-it-ruby'

# optional
- name: mark
  module: 'markdown-it-mark'

# optional
- name: ins
  module: 'markdown-it-ins'

# optional
- name: sup
  module: 'markdown-it-sup'

# optional
- name: sub
  module: 'markdown-it-sub'

# optional
- name: katex
  module: 'markdown-it-katex'
  style-url:
      - 'https://cdn.jsdelivr.net/npm/katex@0.6/dist/katex.min.css'

# optional
- name: css-doodle
  type: render
  module: './markdown-it-plugin/css-doodle'
  script-url:
      - 'https://cdn.jsdelivr.net/npm/css-doodle@0.8/css-doodle.min.js'

# optional
- name: echarts
  type: render
  module: './markdown-it-plugin/echarts'
  script-url:
      - 'https://cdn.jsdelivr.net/npm/echarts@4/dist/echarts.min.js'

# optional
- name: mermaid
  type: render
  module: './markdown-it-plugin/mermaid'
  static:
      - 'mermaid'
  script-url:
      - 'https://cdn.jsdelivr.net/npm/mermaid@8/dist/mermaid.min.js'
      - '/mermaid/index.js'

# optional
- name: timesheet
  type: render
  module: './markdown-it-plugin/timesheet'
  static:
      - 'timesheet'
  style-url:
      - '/timesheet/timesheet.min.css'
      - '/timesheet/compatible.css'
  script-url:
      - '/timesheet/timesheet.min.js'

# optional
- name: smcat
  type: render
  module: './markdown-it-plugin/smcat'

# optional
- name: roughViz
  type: render
  module: './markdown-it-plugin/roughViz'
  script-url:
      - 'https://cdn.jsdelivr.net/npm/@azurity/rough-viz@1/dist/roughviz.min.js'

# optional
- name: asciinema
  type: render
  module: './markdown-it-plugin/asciinema-player'
  static:
      - 'asciinema-player'
  style-url:
      - 'https://cdn.jsdelivr.net/npm/asciinema-player@2/resources/public/css/asciinema-player.min.css'
  script-url:
      - 'https://cdn.jsdelivr.net/npm/asciinema-player@2/resources/public/js/asciinema-player.min.js'
      - '/asciinema-player/loader.js'
