# this need to install express-seesion
- name: session
  module: './session'
  options:
    saveUninitialized: true
  store:
    # please use what you want to use, this only an example
    module: 'connect-sqlite3'
    options:
      dir: '.'
      db: 'session.db'

# this need to install grant-express, and depends on session
- name: OAuth2
  module: './oauth2'
  options:
    # please use what you want to use, this only an example
    github:
      key: da48ba48a570dd5f30a3
      secret: 338a7ce9a323abbc02ccf8eb8af0d92a029da5b7
      nonce: true

- name: Upload
  module: './upload'